### ISSUE TITLE
Error when loading a plugin

### ISSUE THREAD

**Issue by JamieIsGeek** [mdaffa48/MDLib#1]
I have a plugin using the latest version of MDLib, however it errors out whenever it loads or whenever a command is run.

Error: https://hastebin.com/share/kahiyequbo.ruby

Code causing the error:
```java
public static Drop fromConfig(ConfigurationSection section) {
        double chance = section.getDouble("chance");
        Double sellValue = section.get("sell-value") == null ? null : section.getDouble("sell-value");

        ItemBuilder builder = ItemBuilder.fromConfig(section.getConfigurationSection("item"));
        ItemStack stack = builder == null ? null : builder.build();

        List<String> commands = section.getStringList("commands");

        return new Drop(chance, stack, sellValue, commands);
}
```

Looks to maybe be with the xseries dependency in MDLib? Not 100%

Any help would be amazing!

**Comment by JamieIsGeek** [comment]
and the plugin is running papermc version 1.21.1

**Comment by mdaffa48** [comment]
Thank you, I will fix this as soon as possible, to be fair NextGens use the old version of the library and that needs to be updated.
